export const policyText = {
  "en-US": {
    h3: "1. RESPONSIBLE FOR THE PROCESSING OF PERSONAL DATA",
    p1: "This Personal Data Protection Policy will apply to all Databases and / or Files containing Personal Data that are subject to Treatment by CUSTOMERS SOLUTIONS",
    p2: "CUSTOMERS SOLUTIONS, identified with NIT 901430484, domiciled in the city of Barranquilla, with notification address calle 81 No. 71-29, email",
    email: " expericienciacliente@customerssolutions.co",
    p3: " and customer service line 3008586803, is responsible for the processing of the personal data that you have provided through: i) the website ",
    web: " www.customerssolutions.co",
    p4: " ii) The resume completed at the time of your entry as an employee of our company iii) The completion of the supplier registration form prior to the provision of a service or good.",
    h4: "2. PROCESSING AND PURPOSE OF THE DATA",
    p5: "In the development of its commercial activity, and in order to strengthen the relationship with its customers, employees and suppliers, CUSTOMERS SOLUTIONS collects, stores, uses and deletes personal data corresponding to natural and / or legal persons, which are kept on a server managed by our company, in order to:",
    li1: "i) Contact them to provide you with information about the brand, future campaigns, launches, events, welcomes, activities and seasons of discounts or promotions of all our products",
    li2: "ii) Carry out statistical processing of your data",
    li3: "iii) Carry out internal studies on consumption habits.",
    li4: "iv) Knowledge of the employee and his family nucleus",
    li5: "v) Access the employee's information easily and quickly",
    li6: "vi) To send information to their workers and family members",
    li7: "(vii) Establishing business relationships with suppliers",
    li8: "viii) Manage payment processes of those who provide services or supply goods to our organization.",
    h42: "3. RIGHTS OF THE HOLDERS OF PERSONAL DATA",
    p6: " You, as the owner of the personal data, have the following rights, which you can exercise at any time:",
    li9: "a) Know, update and rectify your personal data. This right may be exercised, among others against partial, inaccurate, incomplete, fractional, misleading data, or those whose Treatment is expressly prohibited or has not been authorized;",
    li10: "(b) Request proof of the authorization granted;",
    li11: "c) Be informed about the use that is being given to your personal data;",
    li12: "d) Submit to the Superintendence of Industry and Commerce complaints for violations of the provisions of Law 1581 of 2012 and other regulations that modify, add or complement it",
    li13: " e) Revoke the authorization and / or request the deletion of your data.",
    li14: "f) Access free of charge to the personal data that our company has.",
    h43: "4. RESPONSIBLE AREA",
    p7: "The customer service department of CUSTOMERS SOLUTIONS, is responsible for the attention of requests, queries and claims through which the owner can exercise their rights to know, update, rectify, delete their data and / or revoke the authorization previously granted.",
    h44: "5. PROCEDURE FOR EXERCISING THE RIGHTS OF RIGHTHOLDERS",
    p8: "In exercise of the rights granted by law, you may submit petitions, inquiries and claims through the following channels: email addressed to",
    p9: " or through written communication addressed to the notification address of our organization.",
    p10: "Inquiries will be submitted in cases where you wish to know the personal data contained in our databases and a response will be granted to it, within ten (10) business days following the presentation of the same. In the event that it is impossible for us to respond to you, you will be informed by the same means of the reasons that argue our impossibility, committing us to provide it within the following five (5) business days.",
    p11: "For those cases in which you consider that your personal data should be corrected, updated or deleted, you must submit a claim describing the facts that give rise to it, accompanying it with the documents you want to assert. The term that our company will use to meet your request will be fifteen (15) business days counted from the date of receipt of the same, a term that may be extended for eight (8) additional business days, in cases where it is impossible for us to respond to it, prior notification of the facts that are generating the delay.",
    p12: "In the event that the claim submitted proves incomplete, you will be required within five (5) days to correct the faults. If two (2) months have elapsed from the date of the request without you having submitted the required information, it will be understood that you have withdrawn the claim.",
    h45: "6. TERM",
    p13: "This policy of processing personal data, governs from the first (1st) of January 2021, stating that our database will remain in force until the moment that our company exercises its commercial activity. As the owner of the data you have the right to know, update and rectify your personal data at any time, request proof of the authorization granted, be informed about the use that is being given to your personal data, submit to the Superintendence of Industry and Commerce complaints for violations of the provisions of Law 1581 of 2012,  revoke the authorization and / or request the deletion of your data and access your personal data free of charge.",
    p14: "In the same way, we allow ourselves to inform you that the data requested in relation to your children (s) is information of a public nature, the treatment will respond and respect the best interests of children and adolescents, will ensure respect for their fundamental rights and its granting will correspond to a mere liberality of the parents.",
    btn: "Close this window",
  },
  "es-ES": {
    h3: "1. RESPONSABLE DEL TRATAMIENTO DE LOS DATOS PERSONALES",
    p1: "Esta Política de Protección de Datos Personales se aplicará a todas las Bases de Datos y/o Archivos que contengan Datos Personales que sean objeto de Tratamiento por parte de CUSTOMERS SOLUTIONS",
    p2: "CUSTOMERS SOLUTIONS, identificada con NIT 901430484, domiciliada en la ciudad de Barranquilla, con dirección de notificación calle 81 No. 71-29, correo electrónico",
    email: " expericienciacliente@customerssolutions.co",
    p3: " y línea de atención al cliente 3008586803, es la responsable del tratamiento de los datos personales que usted ha suministrado a través de: i) la página web ",
    web: " www.customerssolutions.co",
    p4: " ii) La hoja de vida diligenciada al momento de su ingreso como empleado de nuestra compañía iii) El diligenciamiento del formulario de registro de proveedores de manera previa a la prestación de un servicio o bien.",
    h4: "2. TRATAMIENTO Y FINALIDAD DE LOS DATOS",
    p5: "En desarrollo de su actividad comercial, y con el fin de fortalecer la relación con sus clientes, empleados y proveedores, CUSTOMERS SOLUTIONS recolecta, almacena, usa y suprime datos personales correspondientes a personas naturales y/o jurídicas, los cuales son conservados en un servidor administrado por nuestra compañía, con la finalidad de:",
    li1: "i) Contactarlos para brindarle información sobre la marca, futuras campañas, lanzamientos, eventos, bienvenidas, actividades y temporadas de descuentos o promociones de todos nuestros productos",
    li2: "ii) Realizar tratamiento estadistico de sus datos",
    li3: "iii) Realizar estudios internos sobre hábitos de consumo.",
    li4: "iv) Conocimiento del empleado y su núcleo familiar",
    li5: "v) Acceder a la información del colaborador de manera fácil y rápida",
    li6: "vi) Para el envío de información a sus trabajadores y familiares",
    li7: "vii) Entablar relaciones comerciales con proveedores",
    li8: "viii) Gestionar procesos de pago de quienes presten servicios o suministren bienes a nuestra organización.",
    h42: "3. DERECHOS DE LOS TITULARES DE LOS DATOS PERSONALES",
    p6: " Usted como titular de los datos personales, tiene los siguientes derechos, los cuales puede ejercer en cualquier momento:",
    li9: "a) Conocer, actualizar y rectificar sus datos personales. Este derecho lo podrá ejercer, entre otros frente a datos parciales, inexactos, incompletos, fraccionados, que induzcan a error, o aquellos cuyo Tratamiento esté expresamente prohibido o no haya sido autorizado;",
    li10: "b) Solicitar prueba de la autorización otorgada;",
    li11: "c) Ser informado respecto del uso que se le está dando a sus datos personales;",
    li12: "d) Presentar ante la Superintendencia de Industria y Comercio quejas por infracciones a lo dispuesto en la Ley 1581 de 2012 y las demás normas que la modifiquen, adicionen o complementen",
    li13: " e) Revocar la autorización y/o solicitar la supresión de sus datos.",
    li14: "f) Acceder en forma gratuita a los datos personales que nuestra sociedad posee.",
    h43: "4. ÁREA RESPONSABLE",
    p7: "El departamento de servicio al cliente de CUSTOMERS SOLUTIONS, tiene a su cargo la atención de peticiones, consultas y reclamos mediante la cual el titular pueda ejercer sus derechos a conocer, actualizar, rectificar, suprimir sus datos y/o revocar la autorización previamente otorgada.",
    h44: "5. PROCEDIMIENTO PARA EJERCER LOS DERECHOS DE LOS TITULARES",
    p8: "En ejercicio de los derechos que la ley otorga, usted podrá elevar peticiones, consultas y reclamos a través de los siguientes canales: correo electrónico dirigido a",
    p9: " o a través de comunicación escrita dirigida al domicilio de notificación de nuestra organización.",
    p10: "Las consultas se presentarán en los casos en que usted desee conocer los datos personales que figuran en nuestras bases de datos y se otorgará respuesta a la misma, dentro de los diez (10) días hábiles siguientes a la presentación de la misma. En caso que se nos imposibilite darle respuesta, se le informará por el mismo medio las razones que argumentan nuestra imposibilidad, comprometiéndonos a proporcionársela dentro de los cinco (5) días hábiles siguientes.",
    p11: "Para aquellos casos en los que usted considere que sus datos personales deban ser corregidos, actualizados o suprimidos, deberá presentar reclamo describiendo los hechos que dan lugar al mismo acompañándolo con los documentos que quiera hacer valer. El término que empleará nuestra compañía para atender su requerimiento será de quince (15) días hábiles contados a partir de la fecha de recepción del mismo, término que podrá prorrogarse por ocho (8) días hábiles adicionales, en los casos en que se nos imposibilite dar respuesta al mismo, previa notificación de los hechos que se encuentran generando la demora.",
    p12: "En caso que el reclamo presentado, resultare incompleto, se le requerirá dentro de los cinco (5) días siguientes para que subsane las fallas. Si transcurridos dos (2) meses a partir de la fecha del requerimiento sin que usted haya presentado la información requerida, se entenderá que ha desistido del reclamo.",
    h45: "6. VIGENCIA",
    p13: "La presente política de tratamiento de datos personales, rige a partir del primero (1º) de enero de 2021, dejándose constancia que nuestra base de datos se mantendrá vigente hasta el momento que nuestra empresa ejerza su actividad comercial. Como titular de los datos usted tiene derecho a conocer, actualizar y rectificar sus datos personales en cualquier momento, solicitar prueba de la autorización otorgada, ser informado respecto del uso que se le está dando a sus datos personales, presentar ante la Superintendencia de Industria y Comercio quejas por infracciones a lo dispuesto en la Ley 1581 de 2012, revocar la autorización y/o solicitar la supresión de sus datos y acceder en forma gratuita a sus datos personales.",
    p14: "De igual forma, nos permitimos informarle que los datos solicitados en relación con su(s) hijos(as) se trata de información de naturaleza pública, el tratamiento responderá y respetará el interés superior de los niños, niñas y adolescentes, asegurará el respeto de sus derechos fundamentales y su otorgamiento corresponderá a una mera liberalidad de los padres.",
    btn: "Cerrar ventana",
  },
};
